name: lockit
version: 0.0.0.0

default-extensions:
  - DerivingStrategies
  - DerivingVia
  - GeneralizedNewtypeDeriving
  - NoImplicitPrelude
  - OverloadedStrings

dependencies:
  - base
  - rio

library:
  source-dirs: src
  dependencies:
      - bytestring
      - github

executables:
  lockit:
    main: Main.hs
    source-dirs: app
    dependencies:
      - lockit
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - lens
      - lockit
      - mtl
      - time
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
